INSERT INTO students (id, first_name, last_name, course_id, grade)
VALUES (1, 'Gabriel', 'Aqua', 1, 'A'),
  (2, 'Jose', 'Dick', 1, 'B'),
  (3, 'Stephanie', 'Vicki', 1, 'A'),
  (4, 'Lizeth', 'Crim', 1, 'B'),
  (5, 'Nestor', 'Dentist', 1, 'B'),
  (6, 'Gabriel', 'Aqua', 3, 'C'),
  (7, 'Jose', 'Dick', 3, 'A'),
  (8, 'Stephanie', 'Vicki', 3, 'B'),
  (9, 'Lizeth', 'Crim', 3, 'C'),
  (10, 'Nestor', 'Dentist', 3, 'B'),
  (11, 'Gabriel', 'Aqua', 6, 'D'),
  (12, 'Jose', 'Dick', 6, 'B'),
  (13, 'Stephanie', 'Vicki', 6, 'A'),
  (14, 'Lizeth', 'Crim', 6, 'C'),
  (15, 'Nestor', 'Dentist', 6, 'A');