INSERT INTO students (first_name, last_name, course_id, grade)
VALUES ('Gabriel', 'Aqua', 1, 'A'),
  ('Jose', 'Dick', 1, 'B'),
  ('Stephanie', 'Vicki', 1, 'A'),
  ('Lizeth', 'Crim', 1, 'B'),
  ('Nestor', 'Dentist', 1, 'B'),
  ('Gabriel', 'Aqua', 3, 'C'),
  ('Jose', 'Dick', 3, 'A'),
  ('Stephanie', 'Vicki', 3, 'B'),
  ('Lizeth', 'Crim', 3, 'C'),
  ('Nestor', 'Dentist', 3, 'B'),
  ('Gabriel', 'Aqua', 6, 'D'),
  ('Jose', 'Dick', 6, 'B'),
  ('Stephanie', 'Vicki', 6, 'A'),
  ('Lizeth', 'Crim', 6, 'C'),
  ('Nestor', 'Dentist', 6, 'A');